#!/bin/sh
### Copyright (C) 2010 Cybozu Labs, Inc., written by Taro Minowa(Higepon) <higepon@labs.cybozu.co.jp>
### All rights reserved.
###
### Redistribution and use in source and binary forms, with or without
### modification, are permitted provided that the following conditions
### are met:
###
### 1. Redistributions of source code must retain the above copyright
###    notice, this list of conditions and the following disclaimer.
### 2. Redistributions in binary form must reproduce the above
###    copyright notice, this list of conditions and the following
###    disclaimer in the documentation and/or other materials provided
###    with the distribution.
###
### THIS SOFTWARE IS PROVIDED BY THE AUTHOR ``AS IS'' AND ANY EXPRESS
### OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
### WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
### ARE DISCLAIMED. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
### DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
### DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
### GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
### INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
### WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
### NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
### SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

. `dirname $0`/mcbench-env
MCBENCH_EBIN_ROOT="${MCBENCH_HOME}/ebin"

opt_concurrency=
opt_command_type=
opt_command_count=
opt_base_data_count=
opt_server=
opt_port=

while getopts 't:n:s:p:b:c:' OPTION
do
  case $OPTION in
  t)    opt_concurrency="$OPTARG"
        ;;
  c)    opt_command_type="$OPTARG"
        ;;
  b)    opt_base_data_count="$OPTARG"
        ;;
  n)    opt_command_count="$OPTARG"
        ;;
  s)    opt_server="$OPTARG"
        ;;
  p)    opt_port="$OPTARG"
        ;;
  ?)    printf "Usage: %s: [-s server] [-p port] [-t number of connection] [-n number of commands] [-c set, get or set_get]\n" $(basename $0) >&2
        exit 2
        ;;
  esac
done

shift $(($OPTIND - 1))
mcbench_concurrency=${opt_concurrency:-10}
mcbench_command_type=${opt_command_type:-get}
mcbench_command_count=${opt_command_count:-100}
mcbench_base_data_count=${opt_base_data_count:-0}
mcbench_server=${opt_server:-"127.0.0.1"}
mcbench_port=${opt_port:-11211}
double_quote="\""
mcbench_server=$double_quote$mcbench_server$double_quote

# we disabled following tw options, since these cause hang up on connect on Mac OSX
#    -kernel inet_default_listen_options [{nodelay,true},{sndbuf,16384},{recbuf,4096}] 
#    -kernel inet_default_connect_options [{nodelay,true}] 


erl +K true \
    +W w \
    -noshell \
    -noinput \
    -pa ${MCBENCH_EBIN_ROOT} \
    -s mcbench_app start \
    -mcbench concurrency ${mcbench_concurrency} \
             command_count ${mcbench_command_count} \
             base_data_count ${mcbench_base_data_count} \
             host ${mcbench_server} \
             port ${mcbench_port} \
             command_type ${mcbench_command_type}

